from psycopg2.extensions import QuotedString as QuotedString, new_array_type as new_array_type, new_type as new_type, register_adapter as register_adapter, register_type as register_type
from typing import Any, Optional

ipaddress: Any

def register_ipaddress(conn_or_curs: Optional[Any] = ...) -> None: ...
def cast_interface(s: Any, cur: Optional[Any] = ...): ...
def cast_network(s: Any, cur: Optional[Any] = ...): ...
def adapt_ipaddress(obj: Any): ...
