import psycopg2
from typing import Any, Optional

class PoolError(psycopg2.Error): ...

class AbstractConnectionPool:
    minconn: Any = ...
    maxconn: Any = ...
    closed: bool = ...
    def __init__(self, minconn: Any, maxconn: Any, *args: Any, **kwargs: Any) -> None: ...

class SimpleConnectionPool(AbstractConnectionPool):
    getconn: Any = ...
    putconn: Any = ...
    closeall: Any = ...

class ThreadedConnectionPool(AbstractConnectionPool):
    def __init__(self, minconn: Any, maxconn: Any, *args: Any, **kwargs: Any) -> None: ...
    def getconn(self, key: Optional[Any] = ...): ...
    def putconn(self, conn: Optional[Any] = ..., key: Optional[Any] = ..., close: bool = ...) -> None: ...
    def closeall(self) -> None: ...
